version: '3'
services:
  web:
    build:
      context: .
      dockerfile: ./docker/web/Dockerfile.ngnix
    depends_on:
      - app
    ports:
      - 80:80
  app:
    build:
      context: .
      dockerfile: ./docker/app/Dockerfile.rails
